feat: improve validation
sashaqred/web-dependency-formatter pull request #40
Opened 2020-05-03 19:47 UTC by sashaqred

Closes #38

2020-05-04 07:55 UTC, Roma36 requested changes

2020-05-04 07:55 UTC, Roma36 commented on src/@modules/DependencyFormatter/components/FileSelector/FileSelector.tsx
> +      ({ file, link }: PackageGroup) => !!file && !!link,
`file || link`
I guess that is what you wanted here

2020-05-04 07:55 UTC, Roma36 commented on src/@modules/DependencyFormatter/components/FileSelector/FileSelector.tsx
> +    if (typeof error === 'string') {
why not just limit function's parameter type to `string` instead of this check?

2020-05-04 09:52 UTC, sashaqred commented on src/@modules/DependencyFormatter/components/FileSelector/FileSelector.tsx
> +      ({ file, link }: PackageGroup) => !!file && !!link,
Sure, weird typo.
But the usage of `!!` is needed to convert to boolean due to strict typings.

2020-05-04 10:00 UTC, sashaqred commented on src/@modules/DependencyFormatter/components/FileSelector/FileSelector.tsx
> +    if (typeof error === 'string') {
In common case `error` always is `string`. 

But here I validate not a field but the whole group. And in this case error of group can be an object after validating the field inside of the group. Probably here could be the better way of group validating and error messaging, but I didn't find it.
Also, in that case, I got warning in console, which I'd like to fix in #39

2020-05-05 08:46 UTC, Roma36 submitted a review, later dismissed

2020-05-05 08:46 UTC, Roma36 commented on src/@modules/DependencyFormatter/components/FileSelector/FileSelector.tsx
> +          const json = await jsonReader(value.package.file);
I'd used destructuring here, rather than having multiple **value.package**

2020-05-05 10:27 UTC, Roma36 approved these changes

2020-05-05 10:40 UTC, merged