feat: initial routing
sashaqred/web-dependency-formatter pull request #6
Opened 2020-04-17 13:17 UTC by sashaqred

Closes #5

2020-04-20 10:54 UTC, Roma36 requested changes

2020-04-20 10:54 UTC, Roma36 commented on src/App/routes/AppRouter.tsx
> +        <Redirect path="*" to="/dependency-formatter" />
why do you need first redirect if this one covers both cases?

2020-04-20 10:54 UTC, Roma36 commented on src/DependencyFormatter/containers/DependencyFormatter/DependencyFormatter.tsx
> +      <Redirect path={`${path}/*`} to={`${path}/upload`} />
same question: why 2 redirects?

2020-04-20 12:47 UTC, sashaqred commented on src/App/routes/AppRouter.tsx
> +        <Redirect path="*" to="/dependency-formatter" />
The first is redundant. Will fix

2020-04-20 12:50 UTC, sashaqred commented on src/DependencyFormatter/containers/DependencyFormatter/DependencyFormatter.tsx
> +      <Redirect path={`${path}/*`} to={`${path}/upload`} />
Here was an issue with redirects. If we come from '/not-existed-path', app'll be redirected to 'dependency-formatter' without the following redirect to '/dependency-formatter/upload'.
But I found the fix.

2020-04-21 11:10 UTC, Roma36 approved these changes

2020-04-21 11:22 UTC, merged